from typing import Dict

from pyjobshop import Solution
from simpyjobshop.modeling import fix_solution
from simpyjobshop.problems import Problem


def evaluator(
    solution: Solution,
    problem: Problem,
    data: Dict[str, int],
    num_workers: int | None = None,
) -> float:
    """
    Evaluates the solution's objective value for the given data.

    By default, num_workers = 1 since that turned out to be faster than more
    workers in a preliminary experiment, for more details:
    # d-krupke.github.io/cpsat-primer/05_parameters.html#parallelization

    Parameters
    ----------
    solution : Solution
        The solution to evaluate.
    problem : Problem
        Problem representation that can create a concrete model.
    data : Dict[str, int]
        The input data generated by the DataGenerator.
    num_workers : int, optional
        Number of workers for parallel evaluation, by default 1.

    Returns
    -------
    float
        The objective value of the solution.
    """

    model = problem.concrete_model(data)
    model = fix_solution(solution, model)
    num_workers = 1 if num_workers is None else num_workers
    results = model.solve(display=False, num_workers=num_workers)
    return results.objective
