from typing import Dict

from pyjobshop import Solution
from pyjobshop.simheuristic.modeling import fix_solution
from pyjobshop.simheuristic.problems.Problem import Problem


def evaluator(
    solution: Solution, problem: Problem, data: Dict[str, int]
) -> float:
    """
    Evaluates the solution for the given data.

    Parameters
    ----------
    solution
        The solution to evaluate.
    problem
        Problem representation that can create a concrete model.
    data
        The input data generated by the DataGenerator.

    Returns
    -------
    float
        The objective value of the solution.
    """

    model = problem.concrete_model(data)
    model = fix_solution(solution, model)
    results = model.solve(display=False)
    return results.objective

def evaluator_stnu(
    solution: Solution, problem: Problem, data: Dict[str, int]
) -> float:
    """
    Evaluates the solution for the given data.

    Parameters
    ----------
    solution
        The solution to evaluate.
    problem
        Problem representation that can create a concrete model.
    data
        The input data generated by the DataGenerator.

    Returns
    -------
    float
        The objective value of the solution.
    """

    # from solution get schedule per resource
    # from problem and schedule per resource build STNU
    # run RTE algorithm to calculate objective
    model = problem.concrete_model(data)
    model = fix_solution(solution, model)
    results = model.solve(display=False)
    return results.objective
