from typing import Callable, Dict

from pyjobshop import Model, Solution
from pyjobshop.simheuristic.modeling import fix_solution, model_builder


def evaluator(
    solution: Solution,
    model_fun: Callable[[Dict[str, int]], Model],
    data: Dict[str, int],
) -> float:
    """
    Evaluates the solution for the given data.

    Parameters
    ----------
    solution
        The solution to evaluate.
    model_fun
        A function that returns a pyjobshop.Model instance for data.
    data
        The input data generated by the DataGenerator.

    Returns
    -------
    float
        The objective value of the solution.
    """

    model = model_builder(model_fun, data)
    model = fix_solution(solution, model)
    results = model.solve(display=False)
    return results.objective
