from typing import Dict

from pyjobshop import Solution
from pyjobshop.simheuristic.modeling import fix_solution, model_builder


def evaluator(solution: Solution, data: Dict[str, int]) -> float:
    """
    Evaluates the solution for the given data.

    Parameters
    ----------
    solution : Solution
        The solution to evaluate.
    data : dict
        The input data generated by the DataGenerator.

    Returns
    -------
    float
        The objective value of the solution.
    """

    model = model_builder(data)
    model = fix_solution(solution, model)
    results = model.solve()
    return results.objective
