import itertools
from typing import Dict, Optional

from pyjobshop import Machine, Model, Solution
from pyjobshop.simheuristic.problems.Problem import Problem
from pyjobshop.simheuristic.utils import find_schedule_per_resource


def fix_solution(solution: Solution, model: Model) -> Model:
    """
    Fixes the order and mode-assignments of tasks in the given model based on
    the given solution.

    Warning: This function modifies the given model in-place. Furthermore, it
    changes the model's internal state by adding new modes and removing the
    original modes. See the "hacky" comments in the code.

    Parameters
    ----------
    solution : Solution
        The solution to apply to the model.
    model : Model
        The model to fix the solution in.

    Returns
    -------
    Model
        The model with fixed order and mode-assignments.
    """

    # Fix mode-assignments by adding the one mode per task
    num_modes = len(model.modes)
    map_to_old_mode = {}
    for task_idx, task in enumerate(solution.tasks):
        mode = model.modes[task.mode]
        map_to_old_mode[task_idx] = task.mode
        resources = [model.resources[idx] for idx in mode.resources]
        model.add_mode(
            model.tasks[task_idx],
            resources,
            duration=mode.duration,
            demands=mode.demands,
        )
    model._map_to_old_mode = map_to_old_mode  # hacky: store mapping for test
    model._modes = model._modes[num_modes:]  # hacky: remove original modes

    # Fix order
    schedule_per_resource = find_schedule_per_resource(solution)
    for sorted_schedule in schedule_per_resource.values():
        for idx1, idx2 in zip(sorted_schedule[:-1], sorted_schedule[1:]):
            task1 = model.tasks[idx1]
            task2 = model.tasks[idx2]
            model.add_end_before_start(task1, task2)

    return model


def find_solution_for_other_data(
    solution: Solution, problem: Problem, data: Dict[str, int]
) -> Solution:
    """
    Transforms the given solution to a new solution that suits that data given
    for the problem at hand. In particular, the new start and end times of
    all the tasks are adjusted to the new data.
    """

    model = problem.concrete_model(data)
    model = fix_solution(solution, model)
    results = model.solve(display=False)
    new_solution = results.best

    # Reset mode choices to original mode indices
    for task in new_solution.tasks:
        task.mode = model._map_to_old_mode[task.mode]

    return new_solution


def model_builder_fix_sol(
    data: Dict[str, int], solution: Optional[Solution] = None
) -> Model:
    """
    Builds and returns a scheduling problem model based on the given data. If
    solution is given, the model will fix the order and mode-assignments of
    corresponding tasks.

    The idea that is exploited here is that the model can be specified faster
    if a solution is given. For example, perhaps without sequence variables.

    Parameters
    ----------
    data : dict
        Input data generated by DataGenerator.
    solution : Solution
        If given, the solution will be used to fix the order and mode-
        assignments of tasks.

    Returns
    -------
    Model
        A configured pyjobshop.Model instance ready for solving.
    """

    b_fix_solution = solution is not None

    # Unpack data
    num_jobs = data["num_jobs"]
    durations = [data[f"duration_{j}"] for j in range(num_jobs)]
    due_dates = [data[f"due_date_{j}"] for j in range(num_jobs)]
    setup_times = {
        (i, j): data[f"setup_time_{i}_{j}"]
        for i, j in itertools.permutations(range(num_jobs), 2)
    }

    # Create model
    model = Model()
    jobs = [model.add_job(due_date=due_dates[j]) for j in range(num_jobs)]
    tasks = [model.add_task(job) for job in jobs]  # one task per job
    machine = model.add_machine()

    # Add modes to the model
    if b_fix_solution:
        for task, duration in zip(tasks, durations):
            model.add_mode(task, machine, duration=duration)
    else:
        for task, duration in zip(tasks, durations):
            model.add_mode(task, machine, duration=duration)

    if b_fix_solution:
        # Fix order
        assert solution is not None
        schedule_per_resource = find_schedule_per_resource(solution)
        for resource_idx, sorted_schedule in schedule_per_resource.items():
            for idx1, idx2 in zip(sorted_schedule[:-1], sorted_schedule[1:]):
                task1 = tasks[idx1]
                task2 = tasks[idx2]

                model.add_end_before_start(task1, task2)

                # Directly add setup times
                resource = model.resources[resource_idx]
                assert isinstance(resource, Machine)
                model.add_setup_time(
                    resource,
                    task1,
                    task2,
                    duration=setup_times[idx1, idx2],
                )
    else:
        # Add sequence-dependent setup times
        for idx1, task1 in enumerate(tasks):
            for idx2, task2 in enumerate(tasks):
                if idx1 == idx2:
                    continue
                model.add_setup_time(
                    machine, task1, task2, duration=setup_times[idx1, idx2]
                )

    return model
