import itertools
from typing import Callable, Dict, Optional

from pyjobshop import Machine, Model, Solution


def find_schedule_per_resource(solution: Solution) -> Dict[int, list[int]]:
    """
    Returns a dictionary mapping resource indices to schedule of task indices.
    """

    schedule_per_resource: dict[int, list[int]] = {}

    # Group tasks by resource
    for task_idx, task in enumerate(solution.tasks):
        for resource_idx in task.resources:
            if resource_idx not in schedule_per_resource:
                schedule_per_resource[resource_idx] = []
            schedule_per_resource[resource_idx].append(task_idx)

    # Sort tasks per resource by start time
    for resource_idx, task_indices in schedule_per_resource.items():
        schedule_per_resource[resource_idx] = sorted(
            task_indices, key=lambda idx: solution.tasks[idx].start
        )

    return schedule_per_resource


def fix_solution(solution: Solution, model: Model) -> Model:
    """
    Fixes the order and mode-assignments of tasks in the given model based on
    the given solution.

    Parameters
    ----------
    solution : Solution
        The solution to apply to the model.
    model : Model
        The model to fix the solution in.

    Returns
    -------
    Model
        The model with fixed order and mode-assignments.
    """

    # Fix mode-assignments by adding the one mode per task
    num_modes = len(model.modes)
    for task_idx, task in enumerate(solution.tasks):
        mode = model.modes[task.mode]
        resources = [model.resources[idx] for idx in mode.resources]
        model.add_mode(
            model.tasks[task_idx],
            resources,
            duration=mode.duration,
            demands=mode.demands,
        )
    model._modes = model._modes[num_modes:]  # hacky: remove original modes

    # Fix order
    schedule_per_resource = find_schedule_per_resource(solution)
    for sorted_schedule in schedule_per_resource.values():
        for idx1, idx2 in zip(sorted_schedule[:-1], sorted_schedule[1:]):
            task1 = model.tasks[idx1]
            task2 = model.tasks[idx2]
            model.add_end_before_start(task1, task2)

    return model


def model_builder(
    model: Callable[[Dict[str, int]], Model], data: Dict[str, int]
) -> Model:
    """
    Builds and returns a scheduling problem model based on the given data.

    Parameters
    ----------
    model : Callable
        A function that returns a pyjobshop.Model instance for data.
    data : dict
        Input data generated by DataGenerator.

    Returns
    -------
    Model
        A configured pyjobshop.Model instance ready for solving.
    """

    return model(data)


def model_builder_fix_sol(
    data: Dict[str, int], solution: Optional[Solution] = None
) -> Model:
    """
    Builds and returns a scheduling problem model based on the given data. If
    solution is given, the model will fix the order and mode-assignments of
    corresponding tasks.

    The idea that is exploited here is that the model can be specified faster
    if a solution is given. For example, perhaps without sequence variables.

    Parameters
    ----------
    data : dict
        Input data generated by DataGenerator.
    solution : Solution
        If given, the solution will be used to fix the order and mode-
        assignments of tasks.

    Returns
    -------
    Model
        A configured pyjobshop.Model instance ready for solving.
    """

    b_fix_solution = solution is not None

    # Unpack data
    num_jobs = data["num_jobs"]
    durations = [data[f"duration_{j}"] for j in range(num_jobs)]
    due_dates = [data[f"due_date_{j}"] for j in range(num_jobs)]
    setup_times = {
        (i, j): data[f"setup_time_{i}_{j}"]
        for i, j in itertools.permutations(range(num_jobs), 2)
    }

    # Create model
    model = Model()
    jobs = [model.add_job(due_date=due_dates[j]) for j in range(num_jobs)]
    tasks = [model.add_task(job) for job in jobs]  # one task per job
    machine = model.add_machine()

    # Add modes to the model
    if b_fix_solution:
        for task, duration in zip(tasks, durations):
            model.add_mode(task, machine, duration=duration)
    else:
        for task, duration in zip(tasks, durations):
            model.add_mode(task, machine, duration=duration)

    if b_fix_solution:
        # Fix order
        assert solution is not None
        schedule_per_resource = find_schedule_per_resource(solution)
        for resource_idx, sorted_schedule in schedule_per_resource.items():
            for idx1, idx2 in zip(sorted_schedule[:-1], sorted_schedule[1:]):
                task1 = tasks[idx1]
                task2 = tasks[idx2]

                model.add_end_before_start(task1, task2)

                # Directly add setup times
                resource = model.resources[resource_idx]
                assert isinstance(resource, Machine)
                model.add_setup_time(
                    resource,
                    task1,
                    task2,
                    duration=setup_times[idx1, idx2],
                )
    else:
        # Add sequence-dependent setup times
        for idx1, task1 in enumerate(tasks):
            for idx2, task2 in enumerate(tasks):
                if idx1 == idx2:
                    continue
                model.add_setup_time(
                    machine, task1, task2, duration=setup_times[idx1, idx2]
                )

    return model
